name: Commitlint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Copy commitlint config
        run: cp commitlint.config.js $GITHUB_WORKSPACE/commitlint.config.js

      - name: Run commitlint
        run: npx commitlint --from=$GITHUB_SHA^ --to=$GITHUB_SHA --config $GITHUB_WORKSPACE/commitlint.config.js