name: Pull Request commitlint
on:
    pull_request:
        types: [opened]
jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm install
            - name: Run commitlint
              run: npx commitlint --from=$GITHUB_SHA^ --to=$GITHUB_SHA --config .commitlintrc.js
